#!/usr/bin/env python

import rospy
from g7_servo_2_control.robin_servo_control_2 import RobinServoControl

if __name__ == '__main__':
	# Initialize
	rospy.init_node('g7_servo_2_control', anonymous=True)

	rsc = RobinServoControl()
	rospy.loginfo("[PAY] Servo control node running")

	try:
		# Loop here until quit
		rospy.spin()
	except rospy.ROSInterruptException:
		pass
	finally:
		rospy.loginfo("[PAY] Servo control shutting down")
		rsc.shutdown()
